# GrassLogin plugin config file
# For more information, please visit the repository of GrassLogin plugin: https://github.com/BlockNeko-11/GrassLogin.

# The config version, which should be the same as the plugin version.
# When the version does not match, the plugin will not be enabled.
version: "${version}"

# Unauthenticated players' behaviour config
unAuthed:
  # The commands that can be executed by unauthenticated players.
  # Note 1: Command aliases are supported.
  # Note 2: Every command here should start with a slash.
  commandWhitelist: ["/l", "/login", "/reg", "/register"]

  # Allow unauthenticated players to chat.
  # Default: false
  # Options: true, false
  allowChat: false

  # Allow unauthenticated players to move.
  # Default: false
  # Options: true, false
  allowMovement: false

  # Allow unauthenticated players to be hurt.
  # Default: false
  # Options: true, false
  noHurt: false

# Database config
database:
  # The type of database.
  # Default: mysql
  # Options: mysql, sqlite
  type: mysql

  # MySQL database config
  mysql:
    # Database host.
    host: localhost

    # Database port.
    port: 3306

    # Database name.
    database: grasslogin

    # Database username.
    username: root

    # Database password.
    password: ""

  # SQLite database config
  sqlite:
    # Path to SQLite database (.db file).
    # Relative to the directory of the config file.
    path: grasslogin.db

# Encryption
# After modifying the following configuration items, players need to re-register.
# Before players re-register, please delete the database table.
# You'd better not modify this!!!
encryption:
  # Encryption method.
  # Default: SHA-512
  # Options: SHA-1, SHA-256, SHA-512, MD5
  method: SHA-512

  # Enable the username encryption.
  # Default: false
  # Options: true, false
  usernameEncryption: false

  # Enable the username encryption fallback.
  # When the username encryption fails, GrassLogin plugin use the plaintext username for storage.
  # Default: true
  # Options: true, false
  usernameEncryptionFallback: true

# Localization language.
# Default: en_us
# Options: en_us, zh_cn
language: en_us
